module Enums = Enums
open Enums

exception InvalidAddressWidth

type zydis_decoder

type zydis_formatter

type zydis_instruction

type immediate = Signed of int64 | Unsigned of int64

type relative = Absolute | Relative

module Operand = struct
  module Action = struct
    type t = int

    let is_read x = x land 0x01 = 0x01

    let is_write x = x land 0x02 = 0x02

    let is_condread x = x land 0x04 = 0x04

    let is_condwrite x = x land 0x08 = 0x08

    let is_read_and_write x = x land 0x03 = 0x03

    let is_condread_and_condwrite x = x land 0x0C = 0x0C

    let is_read_and_condwrite x = x land 0x09 = 0x09

    let is_condread_and_write x = x land 0x06 = 0x06

    let is_any_read x = x land 0x05 <> 0x00

    let is_any_write x = x land 0x0A <> 0x00
  end

  type kind =
    | Unused
    | Reg of register
    | Mem of {
        typ : memory_operand_type;
        segment : register option;
        base : register option;
        index : register option;
        scale : int;
        displacement : int64 option;
      }
    (* segment, offset *)
    | Ptr of int * int32
    | Imm of relative * immediate

  type t = {
    id : int;
    visibility : operand_visibility;
    actions : Action.t;
    encoding : operand_encoding;
    bit_size : int;
    el_ty : element_type;
    el_size : int;
    el_count : int;
    kind : kind;
  }
end

module Attribute = struct
  (* Use Int63.t potentially *)
  type t = int64

  open Int64

  let has_modrm x = logand x 0x01L <> 0L

  let has_sib x = logand x 0x02L <> 0L

  let has_rex x = logand x 0x04L <> 0L

  let has_xop x = logand x 0x08L <> 0L

  let has_vex x = logand x 0x10L <> 0L

  let has_evex x = logand x 0x20L <> 0L

  let has_mvex x = logand x 0x40L <> 0L

  let is_relative x = logand x 0x80L <> 0L

  let is_privileged x = logand x 0x0100L <> 0L

  let accesses_flags x = logand x 0x0010_0000_0000L <> 0L

  let reads_cpu_state x = logand x 0x0020_0000_0000L <> 0L

  let writes_cpu_state x = logand x 0x0040_0000_0000L <> 0L

  let reads_fpu_state x = logand x 0x0080_0000_0000L <> 0L

  let writes_fpu_state x = logand x 0x0100_0000_0000L <> 0L

  let reads_xmm_state x = logand x 0x0200_0000_0000L <> 0L

  let writes_xmm_state x = logand x 0x0400_0000_0000L <> 0L

  let accepts_lock x = logand x 0x0200L <> 0L

  let accepts_rep x = logand x 0x0400L <> 0L

  let accepts_repe x = logand x 0x0800L <> 0L

  let accepts_repne x = logand x 0x1000L <> 0L

  let accepts_bnd x = logand x 0x2000L <> 0L

  let accepts_xacquire x = logand x 0x4000L <> 0L

  let accepts_xrelease x = logand x 0x8000L <> 0L

  let accepts_hle_without_lock x = logand x 0x0001_0000L <> 0L

  let accepts_branch_hints x = logand x 0x0002_0000L <> 0L

  let accepts_segment x = logand x 0x0004_0000L <> 0L

  let has_lock x = logand x 0x0008_0000L <> 0L

  let has_rep x = logand x 0x0010_0000L <> 0L

  let has_repe x = logand x 0x0020_0000L <> 0L

  let has_repne x = logand x 0x0040_0000L <> 0L

  let has_bnd x = logand x 0x0080_0000L <> 0L

  let has_xacquire x = logand x 0x0100_0000L <> 0L

  let has_xrelease x = logand x 0x0200_0000L <> 0L

  let has_branch_not_taken x = logand x 0x0400_0000L <> 0L

  let has_branch_taken x = logand x 0x0800_0000L <> 0L

  let has_segment x = logand x 0x3_F000_0000L <> 0L

  let has_segment_cs x = logand x 0x1000_0000L <> 0L

  let has_segment_ss x = logand x 0x2000_0000L <> 0L

  let has_segment_ds x = logand x 0x4000_0000L <> 0L

  let has_segment_es x = logand x 0x8000_0000L <> 0L

  let has_segment_fs x = logand x 0x0001_0000_0000L <> 0L

  let has_segment_gs x = logand x 0x0002_0000_0000L <> 0L

  let has_operand_size x = logand x 0x0004_0000_0000L <> 0L

  let has_address_size x = logand x 0x0008_0000_0000L <> 0L

  let has_branch_hints x = logand x 0x0C00_0000L <> 0L

  let has_any_rep x = logand x 0x0070_0000L <> 0L

  let accepts_any_rep x = logand x 0x1C00L <> 0L

  let touches_cpu_state x = logand x 0x0060_0000_0000L <> 0L

  let touches_fpu_state x = logand x 0x0180_0000_0000L <> 0L

  let touches_xmm_state x = logand x 0x0600_0000_0000L <> 0L
end

module Instruction = struct
  type avx

  type meta = {
    category : instruction_category;
    isa_set : isaset;
    isa_ext : isaext;
    branch_type : branch_type option;
    exception_class : exception_class option;
  }

  type raw

  type t = {
    mode : machine_mode;
    mnemonic : mnemonic;
    length : int;
    encoding : instruction_encoding;
    opcode_map : opcode_map;
    opcode : int;
    stack_width : int;
    operand_width : int;
    address_width : int;
    operands : Operand.t Array.t;
    attributes : Attribute.t;
    flags : (cpuflag * cpuflag_action) Array.t;
    avx : avx;
    meta : meta;
    raw : raw;
    raw_insn : zydis_instruction;
  }
end

external zydis_decoder_init : machine_mode -> address_width -> zydis_decoder
  = "zydis_decoder_init"

external zydis_decoder_enable : zydis_decoder -> machine_mode -> bool -> unit
  = "zydis_decoder_enable"

external zydis_decoder_decode_long :
  zydis_decoder -> bytes -> int -> Instruction.t option
  = "zydis_decoder_decode_long"

external zydis_decoder_decode_native :
  zydis_decoder -> bytes -> nativeint -> Instruction.t option
  = "zydis_decoder_decode_native"

module Decoder = struct
  type t = zydis_decoder

  let create ~mode ~width =
    match width with
    | 16 -> zydis_decoder_init mode AddressWidth16
    | 32 -> zydis_decoder_init mode AddressWidth32
    | 64 -> zydis_decoder_init mode AddressWidth64
    | _ -> raise InvalidAddressWidth

  let disable decoder mode = zydis_decoder_enable decoder mode false

  let enable decoder mode = zydis_decoder_enable decoder mode true

  let decode decoder buffer offset =
    zydis_decoder_decode_long decoder buffer offset

  let decode_n decoder buffer offset =
    zydis_decoder_decode_native decoder buffer offset

  let set_enabled decoder mode v = zydis_decoder_enable decoder mode v
end

external zydis_formatter_init : formatter_style -> zydis_formatter
  = "zydis_formatter_init"

external zydis_formatter_format_insn :
  zydis_formatter -> zydis_instruction -> int64 -> string
  = "zydis_formatter_format_insn"

module Formatter = struct
  type t = zydis_formatter

  open Instruction

  let create ~style = zydis_formatter_init style

  let format formatter { raw_insn; _ } =
    zydis_formatter_format_insn formatter raw_insn (-1L)

  let format_addr formatter { raw_insn; _ } addr =
    zydis_formatter_format_insn formatter raw_insn addr
end

module type Memory = sig
  type t

  type phys = int
  type virt = int

  val create : bytes -> t

  val phys_of_virt : t -> virt -> phys

  val bytes : t -> bytes

  val load64 : t -> virt -> int64 option
end

module LinearMemory : Memory = struct
  type t = bytes

  type phys = int
  type virt = int

  let create x = x

  let phys_of_virt _ x = x

  let bytes t = t

  let load64 _t _offs = None (* Some (Bytes.get_int64_le x offs) *)
end

module Recursive (M : Memory) = struct
  let compare_int a b =
    let int_of_bool b = Obj.magic b in
    int_of_bool (a > b) - int_of_bool (a < b)

  module IntOrder : Set.OrderedType with type t = int = struct
    type t = int
    let compare = compare_int
  end

  module IntSet = Set.Make (IntOrder)

  type t = {
    d : Decoder.t;
    mem : M.t;
    mutable seen : IntSet.t;
    }

  type behav =
    | Continue
    | ContinueAt of M.virt
    | Stop

  let create d mem = {d; mem; seen = IntSet.empty}

  let disassemble offs f t =
    let get_imm rip kind = match kind with
      | Operand.Imm (Relative, Signed imm) | Operand.Imm (Relative, Unsigned imm) ->
        Some ((Int64.to_int imm) + rip)
      | Operand.Imm (Absolute, Signed imm) | Operand.Imm (Absolute, Unsigned imm) ->
        Some (Int64.to_int imm)
      | Operand.Mem {base = Some RIP; displacement = Some disp; _} ->
        let offs = (Int64.to_int disp) + rip in
        M.load64 t.mem offs |> Option.map Int64.to_int
      | _ -> None
    in
    let rec go = function
      | [] -> ()
      | x :: xs when IntSet.mem x t.seen -> go xs
      | x :: xs ->
        (* TODO: Keep the set smaller by only adding branch targets. *)
        t.seen <- IntSet.add x t.seen;
        let buffer = M.bytes t.mem in
        let phys = M.phys_of_virt t.mem x in
        match Decoder.decode t.d buffer phys with
        | None -> go xs
        | Some insn ->
           match f x insn with
           | Continue ->
              branch insn (x + insn.length) xs
           | ContinueAt rip ->
              branch insn rip xs
           | Stop -> ()
    and branch insn rip xs =
      match insn.meta.category with
      | CALL | COND_BR -> (match get_imm rip insn.operands.(0).kind with
                           | Some imm -> go (rip :: imm :: xs)
                           | None -> go (rip :: xs)
                          )
      | RET -> go xs
      | _ -> match insn.mnemonic with
             | JMP -> (match get_imm rip insn.operands.(0).kind with
                       | Some imm -> go (imm :: xs)
                       | None -> go xs
                      )
             | _ -> go (rip :: xs)
    in
    go [offs]
end

(* Pretty printing functions {{{ *)

let str_of_mnemonic (x:Enums.mnemonic) = match x with
  | INVALID -> "INVALID"
  | AAA -> "AAA"
  | AAD -> "AAD"
  | AAM -> "AAM"
  | AAS -> "AAS"
  | ADC -> "ADC"
  | ADCX -> "ADCX"
  | ADD -> "ADD"
  | ADDPD -> "ADDPD"
  | ADDPS -> "ADDPS"
  | ADDSD -> "ADDSD"
  | ADDSS -> "ADDSS"
  | ADDSUBPD -> "ADDSUBPD"
  | ADDSUBPS -> "ADDSUBPS"
  | ADOX -> "ADOX"
  | AESDEC -> "AESDEC"
  | AESDECLAST -> "AESDECLAST"
  | AESENC -> "AESENC"
  | AESENCLAST -> "AESENCLAST"
  | AESIMC -> "AESIMC"
  | AESKEYGENASSIST -> "AESKEYGENASSIST"
  | AND -> "AND"
  | ANDN -> "ANDN"
  | ANDNPD -> "ANDNPD"
  | ANDNPS -> "ANDNPS"
  | ANDPD -> "ANDPD"
  | ANDPS -> "ANDPS"
  | ARPL -> "ARPL"
  | BEXTR -> "BEXTR"
  | BLCFILL -> "BLCFILL"
  | BLCI -> "BLCI"
  | BLCIC -> "BLCIC"
  | BLCMSK -> "BLCMSK"
  | BLCS -> "BLCS"
  | BLENDPD -> "BLENDPD"
  | BLENDPS -> "BLENDPS"
  | BLENDVPD -> "BLENDVPD"
  | BLENDVPS -> "BLENDVPS"
  | BLSFILL -> "BLSFILL"
  | BLSI -> "BLSI"
  | BLSIC -> "BLSIC"
  | BLSMSK -> "BLSMSK"
  | BLSR -> "BLSR"
  | BNDCL -> "BNDCL"
  | BNDCN -> "BNDCN"
  | BNDCU -> "BNDCU"
  | BNDLDX -> "BNDLDX"
  | BNDMK -> "BNDMK"
  | BNDMOV -> "BNDMOV"
  | BNDSTX -> "BNDSTX"
  | BOUND -> "BOUND"
  | BSF -> "BSF"
  | BSR -> "BSR"
  | BSWAP -> "BSWAP"
  | BT -> "BT"
  | BTC -> "BTC"
  | BTR -> "BTR"
  | BTS -> "BTS"
  | BZHI -> "BZHI"
  | CALL -> "CALL"
  | CBW -> "CBW"
  | CDQ -> "CDQ"
  | CDQE -> "CDQE"
  | CLAC -> "CLAC"
  | CLC -> "CLC"
  | CLD -> "CLD"
  | CLDEMOTE -> "CLDEMOTE"
  | CLEVICT0 -> "CLEVICT0"
  | CLEVICT1 -> "CLEVICT1"
  | CLFLUSH -> "CLFLUSH"
  | CLFLUSHOPT -> "CLFLUSHOPT"
  | CLGI -> "CLGI"
  | CLI -> "CLI"
  | CLRSSBSY -> "CLRSSBSY"
  | CLTS -> "CLTS"
  | CLWB -> "CLWB"
  | CLZERO -> "CLZERO"
  | CMC -> "CMC"
  | CMOVB -> "CMOVB"
  | CMOVBE -> "CMOVBE"
  | CMOVL -> "CMOVL"
  | CMOVLE -> "CMOVLE"
  | CMOVNB -> "CMOVNB"
  | CMOVNBE -> "CMOVNBE"
  | CMOVNL -> "CMOVNL"
  | CMOVNLE -> "CMOVNLE"
  | CMOVNO -> "CMOVNO"
  | CMOVNP -> "CMOVNP"
  | CMOVNS -> "CMOVNS"
  | CMOVNZ -> "CMOVNZ"
  | CMOVO -> "CMOVO"
  | CMOVP -> "CMOVP"
  | CMOVS -> "CMOVS"
  | CMOVZ -> "CMOVZ"
  | CMP -> "CMP"
  | CMPPD -> "CMPPD"
  | CMPPS -> "CMPPS"
  | CMPSB -> "CMPSB"
  | CMPSD -> "CMPSD"
  | CMPSQ -> "CMPSQ"
  | CMPSS -> "CMPSS"
  | CMPSW -> "CMPSW"
  | CMPXCHG -> "CMPXCHG"
  | CMPXCHG16B -> "CMPXCHG16B"
  | CMPXCHG8B -> "CMPXCHG8B"
  | COMISD -> "COMISD"
  | COMISS -> "COMISS"
  | CPUID -> "CPUID"
  | CQO -> "CQO"
  | CRC32 -> "CRC32"
  | CVTDQ2PD -> "CVTDQ2PD"
  | CVTDQ2PS -> "CVTDQ2PS"
  | CVTPD2DQ -> "CVTPD2DQ"
  | CVTPD2PI -> "CVTPD2PI"
  | CVTPD2PS -> "CVTPD2PS"
  | CVTPI2PD -> "CVTPI2PD"
  | CVTPI2PS -> "CVTPI2PS"
  | CVTPS2DQ -> "CVTPS2DQ"
  | CVTPS2PD -> "CVTPS2PD"
  | CVTPS2PI -> "CVTPS2PI"
  | CVTSD2SI -> "CVTSD2SI"
  | CVTSD2SS -> "CVTSD2SS"
  | CVTSI2SD -> "CVTSI2SD"
  | CVTSI2SS -> "CVTSI2SS"
  | CVTSS2SD -> "CVTSS2SD"
  | CVTSS2SI -> "CVTSS2SI"
  | CVTTPD2DQ -> "CVTTPD2DQ"
  | CVTTPD2PI -> "CVTTPD2PI"
  | CVTTPS2DQ -> "CVTTPS2DQ"
  | CVTTPS2PI -> "CVTTPS2PI"
  | CVTTSD2SI -> "CVTTSD2SI"
  | CVTTSS2SI -> "CVTTSS2SI"
  | CWD -> "CWD"
  | CWDE -> "CWDE"
  | DAA -> "DAA"
  | DAS -> "DAS"
  | DEC -> "DEC"
  | DELAY -> "DELAY"
  | DIV -> "DIV"
  | DIVPD -> "DIVPD"
  | DIVPS -> "DIVPS"
  | DIVSD -> "DIVSD"
  | DIVSS -> "DIVSS"
  | DPPD -> "DPPD"
  | DPPS -> "DPPS"
  | EMMS -> "EMMS"
  | ENCLS -> "ENCLS"
  | ENCLU -> "ENCLU"
  | ENCLV -> "ENCLV"
  | ENDBR32 -> "ENDBR32"
  | ENDBR64 -> "ENDBR64"
  | ENQCMD -> "ENQCMD"
  | ENQCMDS -> "ENQCMDS"
  | ENTER -> "ENTER"
  | EXTRACTPS -> "EXTRACTPS"
  | EXTRQ -> "EXTRQ"
  | F2XM1 -> "F2XM1"
  | FABS -> "FABS"
  | FADD -> "FADD"
  | FADDP -> "FADDP"
  | FBLD -> "FBLD"
  | FBSTP -> "FBSTP"
  | FCHS -> "FCHS"
  | FCMOVB -> "FCMOVB"
  | FCMOVBE -> "FCMOVBE"
  | FCMOVE -> "FCMOVE"
  | FCMOVNB -> "FCMOVNB"
  | FCMOVNBE -> "FCMOVNBE"
  | FCMOVNE -> "FCMOVNE"
  | FCMOVNU -> "FCMOVNU"
  | FCMOVU -> "FCMOVU"
  | FCOM -> "FCOM"
  | FCOMI -> "FCOMI"
  | FCOMIP -> "FCOMIP"
  | FCOMP -> "FCOMP"
  | FCOMPP -> "FCOMPP"
  | FCOS -> "FCOS"
  | FDECSTP -> "FDECSTP"
  | FDISI8087_NOP -> "FDISI8087_NOP"
  | FDIV -> "FDIV"
  | FDIVP -> "FDIVP"
  | FDIVR -> "FDIVR"
  | FDIVRP -> "FDIVRP"
  | FEMMS -> "FEMMS"
  | FENI8087_NOP -> "FENI8087_NOP"
  | FFREE -> "FFREE"
  | FFREEP -> "FFREEP"
  | FIADD -> "FIADD"
  | FICOM -> "FICOM"
  | FICOMP -> "FICOMP"
  | FIDIV -> "FIDIV"
  | FIDIVR -> "FIDIVR"
  | FILD -> "FILD"
  | FIMUL -> "FIMUL"
  | FINCSTP -> "FINCSTP"
  | FIST -> "FIST"
  | FISTP -> "FISTP"
  | FISTTP -> "FISTTP"
  | FISUB -> "FISUB"
  | FISUBR -> "FISUBR"
  | FLD -> "FLD"
  | FLD1 -> "FLD1"
  | FLDCW -> "FLDCW"
  | FLDENV -> "FLDENV"
  | FLDL2E -> "FLDL2E"
  | FLDL2T -> "FLDL2T"
  | FLDLG2 -> "FLDLG2"
  | FLDLN2 -> "FLDLN2"
  | FLDPI -> "FLDPI"
  | FLDZ -> "FLDZ"
  | FMUL -> "FMUL"
  | FMULP -> "FMULP"
  | FNCLEX -> "FNCLEX"
  | FNINIT -> "FNINIT"
  | FNOP -> "FNOP"
  | FNSAVE -> "FNSAVE"
  | FNSTCW -> "FNSTCW"
  | FNSTENV -> "FNSTENV"
  | FNSTSW -> "FNSTSW"
  | FPATAN -> "FPATAN"
  | FPREM -> "FPREM"
  | FPREM1 -> "FPREM1"
  | FPTAN -> "FPTAN"
  | FRNDINT -> "FRNDINT"
  | FRSTOR -> "FRSTOR"
  | FSCALE -> "FSCALE"
  | FSETPM287_NOP -> "FSETPM287_NOP"
  | FSIN -> "FSIN"
  | FSINCOS -> "FSINCOS"
  | FSQRT -> "FSQRT"
  | FST -> "FST"
  | FSTP -> "FSTP"
  | FSTPNCE -> "FSTPNCE"
  | FSUB -> "FSUB"
  | FSUBP -> "FSUBP"
  | FSUBR -> "FSUBR"
  | FSUBRP -> "FSUBRP"
  | FTST -> "FTST"
  | FUCOM -> "FUCOM"
  | FUCOMI -> "FUCOMI"
  | FUCOMIP -> "FUCOMIP"
  | FUCOMP -> "FUCOMP"
  | FUCOMPP -> "FUCOMPP"
  | FWAIT -> "FWAIT"
  | FXAM -> "FXAM"
  | FXCH -> "FXCH"
  | FXRSTOR -> "FXRSTOR"
  | FXRSTOR64 -> "FXRSTOR64"
  | FXSAVE -> "FXSAVE"
  | FXSAVE64 -> "FXSAVE64"
  | FXTRACT -> "FXTRACT"
  | FYL2X -> "FYL2X"
  | FYL2XP1 -> "FYL2XP1"
  | GETSEC -> "GETSEC"
  | GF2P8AFFINEINVQB -> "GF2P8AFFINEINVQB"
  | GF2P8AFFINEQB -> "GF2P8AFFINEQB"
  | GF2P8MULB -> "GF2P8MULB"
  | HADDPD -> "HADDPD"
  | HADDPS -> "HADDPS"
  | HLT -> "HLT"
  | HSUBPD -> "HSUBPD"
  | HSUBPS -> "HSUBPS"
  | IDIV -> "IDIV"
  | IMUL -> "IMUL"
  | IN -> "IN"
  | INC -> "INC"
  | INCSSPD -> "INCSSPD"
  | INCSSPQ -> "INCSSPQ"
  | INSB -> "INSB"
  | INSD -> "INSD"
  | INSERTPS -> "INSERTPS"
  | INSERTQ -> "INSERTQ"
  | INSW -> "INSW"
  | INT -> "INT"
  | INT1 -> "INT1"
  | INT3 -> "INT3"
  | INTO -> "INTO"
  | INVD -> "INVD"
  | INVEPT -> "INVEPT"
  | INVLPG -> "INVLPG"
  | INVLPGA -> "INVLPGA"
  | INVPCID -> "INVPCID"
  | INVVPID -> "INVVPID"
  | IRET -> "IRET"
  | IRETD -> "IRETD"
  | IRETQ -> "IRETQ"
  | JB -> "JB"
  | JBE -> "JBE"
  | JCXZ -> "JCXZ"
  | JECXZ -> "JECXZ"
  | JKNZD -> "JKNZD"
  | JKZD -> "JKZD"
  | JL -> "JL"
  | JLE -> "JLE"
  | JMP -> "JMP"
  | JNB -> "JNB"
  | JNBE -> "JNBE"
  | JNL -> "JNL"
  | JNLE -> "JNLE"
  | JNO -> "JNO"
  | JNP -> "JNP"
  | JNS -> "JNS"
  | JNZ -> "JNZ"
  | JO -> "JO"
  | JP -> "JP"
  | JRCXZ -> "JRCXZ"
  | JS -> "JS"
  | JZ -> "JZ"
  | KADDB -> "KADDB"
  | KADDD -> "KADDD"
  | KADDQ -> "KADDQ"
  | KADDW -> "KADDW"
  | KAND -> "KAND"
  | KANDB -> "KANDB"
  | KANDD -> "KANDD"
  | KANDN -> "KANDN"
  | KANDNB -> "KANDNB"
  | KANDND -> "KANDND"
  | KANDNQ -> "KANDNQ"
  | KANDNR -> "KANDNR"
  | KANDNW -> "KANDNW"
  | KANDQ -> "KANDQ"
  | KANDW -> "KANDW"
  | KCONCATH -> "KCONCATH"
  | KCONCATL -> "KCONCATL"
  | KEXTRACT -> "KEXTRACT"
  | KMERGE2L1H -> "KMERGE2L1H"
  | KMERGE2L1L -> "KMERGE2L1L"
  | KMOV -> "KMOV"
  | KMOVB -> "KMOVB"
  | KMOVD -> "KMOVD"
  | KMOVQ -> "KMOVQ"
  | KMOVW -> "KMOVW"
  | KNOT -> "KNOT"
  | KNOTB -> "KNOTB"
  | KNOTD -> "KNOTD"
  | KNOTQ -> "KNOTQ"
  | KNOTW -> "KNOTW"
  | KOR -> "KOR"
  | KORB -> "KORB"
  | KORD -> "KORD"
  | KORQ -> "KORQ"
  | KORTEST -> "KORTEST"
  | KORTESTB -> "KORTESTB"
  | KORTESTD -> "KORTESTD"
  | KORTESTQ -> "KORTESTQ"
  | KORTESTW -> "KORTESTW"
  | KORW -> "KORW"
  | KSHIFTLB -> "KSHIFTLB"
  | KSHIFTLD -> "KSHIFTLD"
  | KSHIFTLQ -> "KSHIFTLQ"
  | KSHIFTLW -> "KSHIFTLW"
  | KSHIFTRB -> "KSHIFTRB"
  | KSHIFTRD -> "KSHIFTRD"
  | KSHIFTRQ -> "KSHIFTRQ"
  | KSHIFTRW -> "KSHIFTRW"
  | KTESTB -> "KTESTB"
  | KTESTD -> "KTESTD"
  | KTESTQ -> "KTESTQ"
  | KTESTW -> "KTESTW"
  | KUNPCKBW -> "KUNPCKBW"
  | KUNPCKDQ -> "KUNPCKDQ"
  | KUNPCKWD -> "KUNPCKWD"
  | KXNOR -> "KXNOR"
  | KXNORB -> "KXNORB"
  | KXNORD -> "KXNORD"
  | KXNORQ -> "KXNORQ"
  | KXNORW -> "KXNORW"
  | KXOR -> "KXOR"
  | KXORB -> "KXORB"
  | KXORD -> "KXORD"
  | KXORQ -> "KXORQ"
  | KXORW -> "KXORW"
  | LAHF -> "LAHF"
  | LAR -> "LAR"
  | LDDQU -> "LDDQU"
  | LDMXCSR -> "LDMXCSR"
  | LDS -> "LDS"
  | LEA -> "LEA"
  | LEAVE -> "LEAVE"
  | LES -> "LES"
  | LFENCE -> "LFENCE"
  | LFS -> "LFS"
  | LGDT -> "LGDT"
  | LGS -> "LGS"
  | LIDT -> "LIDT"
  | LLDT -> "LLDT"
  | LLWPCB -> "LLWPCB"
  | LMSW -> "LMSW"
  | LODSB -> "LODSB"
  | LODSD -> "LODSD"
  | LODSQ -> "LODSQ"
  | LODSW -> "LODSW"
  | LOOP -> "LOOP"
  | LOOPE -> "LOOPE"
  | LOOPNE -> "LOOPNE"
  | LSL -> "LSL"
  | LSS -> "LSS"
  | LTR -> "LTR"
  | LWPINS -> "LWPINS"
  | LWPVAL -> "LWPVAL"
  | LZCNT -> "LZCNT"
  | MASKMOVDQU -> "MASKMOVDQU"
  | MASKMOVQ -> "MASKMOVQ"
  | MAXPD -> "MAXPD"
  | MAXPS -> "MAXPS"
  | MAXSD -> "MAXSD"
  | MAXSS -> "MAXSS"
  | MFENCE -> "MFENCE"
  | MINPD -> "MINPD"
  | MINPS -> "MINPS"
  | MINSD -> "MINSD"
  | MINSS -> "MINSS"
  | MONITOR -> "MONITOR"
  | MONITORX -> "MONITORX"
  | MONTMUL -> "MONTMUL"
  | MOV -> "MOV"
  | MOVAPD -> "MOVAPD"
  | MOVAPS -> "MOVAPS"
  | MOVBE -> "MOVBE"
  | MOVD -> "MOVD"
  | MOVDDUP -> "MOVDDUP"
  | MOVDIR64B -> "MOVDIR64B"
  | MOVDIRI -> "MOVDIRI"
  | MOVDQ2Q -> "MOVDQ2Q"
  | MOVDQA -> "MOVDQA"
  | MOVDQU -> "MOVDQU"
  | MOVHLPS -> "MOVHLPS"
  | MOVHPD -> "MOVHPD"
  | MOVHPS -> "MOVHPS"
  | MOVLHPS -> "MOVLHPS"
  | MOVLPD -> "MOVLPD"
  | MOVLPS -> "MOVLPS"
  | MOVMSKPD -> "MOVMSKPD"
  | MOVMSKPS -> "MOVMSKPS"
  | MOVNTDQ -> "MOVNTDQ"
  | MOVNTDQA -> "MOVNTDQA"
  | MOVNTI -> "MOVNTI"
  | MOVNTPD -> "MOVNTPD"
  | MOVNTPS -> "MOVNTPS"
  | MOVNTQ -> "MOVNTQ"
  | MOVNTSD -> "MOVNTSD"
  | MOVNTSS -> "MOVNTSS"
  | MOVQ -> "MOVQ"
  | MOVQ2DQ -> "MOVQ2DQ"
  | MOVSB -> "MOVSB"
  | MOVSD -> "MOVSD"
  | MOVSHDUP -> "MOVSHDUP"
  | MOVSLDUP -> "MOVSLDUP"
  | MOVSQ -> "MOVSQ"
  | MOVSS -> "MOVSS"
  | MOVSW -> "MOVSW"
  | MOVSX -> "MOVSX"
  | MOVSXD -> "MOVSXD"
  | MOVUPD -> "MOVUPD"
  | MOVUPS -> "MOVUPS"
  | MOVZX -> "MOVZX"
  | MPSADBW -> "MPSADBW"
  | MUL -> "MUL"
  | MULPD -> "MULPD"
  | MULPS -> "MULPS"
  | MULSD -> "MULSD"
  | MULSS -> "MULSS"
  | MULX -> "MULX"
  | MWAIT -> "MWAIT"
  | MWAITX -> "MWAITX"
  | NEG -> "NEG"
  | NOP -> "NOP"
  | NOT -> "NOT"
  | OR -> "OR"
  | ORPD -> "ORPD"
  | ORPS -> "ORPS"
  | OUT -> "OUT"
  | OUTSB -> "OUTSB"
  | OUTSD -> "OUTSD"
  | OUTSW -> "OUTSW"
  | PABSB -> "PABSB"
  | PABSD -> "PABSD"
  | PABSW -> "PABSW"
  | PACKSSDW -> "PACKSSDW"
  | PACKSSWB -> "PACKSSWB"
  | PACKUSDW -> "PACKUSDW"
  | PACKUSWB -> "PACKUSWB"
  | PADDB -> "PADDB"
  | PADDD -> "PADDD"
  | PADDQ -> "PADDQ"
  | PADDSB -> "PADDSB"
  | PADDSW -> "PADDSW"
  | PADDUSB -> "PADDUSB"
  | PADDUSW -> "PADDUSW"
  | PADDW -> "PADDW"
  | PALIGNR -> "PALIGNR"
  | PAND -> "PAND"
  | PANDN -> "PANDN"
  | PAUSE -> "PAUSE"
  | PAVGB -> "PAVGB"
  | PAVGUSB -> "PAVGUSB"
  | PAVGW -> "PAVGW"
  | PBLENDVB -> "PBLENDVB"
  | PBLENDW -> "PBLENDW"
  | PCLMULQDQ -> "PCLMULQDQ"
  | PCMPEQB -> "PCMPEQB"
  | PCMPEQD -> "PCMPEQD"
  | PCMPEQQ -> "PCMPEQQ"
  | PCMPEQW -> "PCMPEQW"
  | PCMPESTRI -> "PCMPESTRI"
  | PCMPESTRM -> "PCMPESTRM"
  | PCMPGTB -> "PCMPGTB"
  | PCMPGTD -> "PCMPGTD"
  | PCMPGTQ -> "PCMPGTQ"
  | PCMPGTW -> "PCMPGTW"
  | PCMPISTRI -> "PCMPISTRI"
  | PCMPISTRM -> "PCMPISTRM"
  | PCONFIG -> "PCONFIG"
  | PDEP -> "PDEP"
  | PEXT -> "PEXT"
  | PEXTRB -> "PEXTRB"
  | PEXTRD -> "PEXTRD"
  | PEXTRQ -> "PEXTRQ"
  | PEXTRW -> "PEXTRW"
  | PF2ID -> "PF2ID"
  | PF2IW -> "PF2IW"
  | PFACC -> "PFACC"
  | PFADD -> "PFADD"
  | PFCMPEQ -> "PFCMPEQ"
  | PFCMPGE -> "PFCMPGE"
  | PFCMPGT -> "PFCMPGT"
  | PFCPIT1 -> "PFCPIT1"
  | PFMAX -> "PFMAX"
  | PFMIN -> "PFMIN"
  | PFMUL -> "PFMUL"
  | PFNACC -> "PFNACC"
  | PFPNACC -> "PFPNACC"
  | PFRCP -> "PFRCP"
  | PFRCPIT2 -> "PFRCPIT2"
  | PFRSQIT1 -> "PFRSQIT1"
  | PFSQRT -> "PFSQRT"
  | PFSUB -> "PFSUB"
  | PFSUBR -> "PFSUBR"
  | PHADDD -> "PHADDD"
  | PHADDSW -> "PHADDSW"
  | PHADDW -> "PHADDW"
  | PHMINPOSUW -> "PHMINPOSUW"
  | PHSUBD -> "PHSUBD"
  | PHSUBSW -> "PHSUBSW"
  | PHSUBW -> "PHSUBW"
  | PI2FD -> "PI2FD"
  | PI2FW -> "PI2FW"
  | PINSRB -> "PINSRB"
  | PINSRD -> "PINSRD"
  | PINSRQ -> "PINSRQ"
  | PINSRW -> "PINSRW"
  | PMADDUBSW -> "PMADDUBSW"
  | PMADDWD -> "PMADDWD"
  | PMAXSB -> "PMAXSB"
  | PMAXSD -> "PMAXSD"
  | PMAXSW -> "PMAXSW"
  | PMAXUB -> "PMAXUB"
  | PMAXUD -> "PMAXUD"
  | PMAXUW -> "PMAXUW"
  | PMINSB -> "PMINSB"
  | PMINSD -> "PMINSD"
  | PMINSW -> "PMINSW"
  | PMINUB -> "PMINUB"
  | PMINUD -> "PMINUD"
  | PMINUW -> "PMINUW"
  | PMOVMSKB -> "PMOVMSKB"
  | PMOVSXBD -> "PMOVSXBD"
  | PMOVSXBQ -> "PMOVSXBQ"
  | PMOVSXBW -> "PMOVSXBW"
  | PMOVSXDQ -> "PMOVSXDQ"
  | PMOVSXWD -> "PMOVSXWD"
  | PMOVSXWQ -> "PMOVSXWQ"
  | PMOVZXBD -> "PMOVZXBD"
  | PMOVZXBQ -> "PMOVZXBQ"
  | PMOVZXBW -> "PMOVZXBW"
  | PMOVZXDQ -> "PMOVZXDQ"
  | PMOVZXWD -> "PMOVZXWD"
  | PMOVZXWQ -> "PMOVZXWQ"
  | PMULDQ -> "PMULDQ"
  | PMULHRSW -> "PMULHRSW"
  | PMULHRW -> "PMULHRW"
  | PMULHUW -> "PMULHUW"
  | PMULHW -> "PMULHW"
  | PMULLD -> "PMULLD"
  | PMULLW -> "PMULLW"
  | PMULUDQ -> "PMULUDQ"
  | POP -> "POP"
  | POPA -> "POPA"
  | POPAD -> "POPAD"
  | POPCNT -> "POPCNT"
  | POPF -> "POPF"
  | POPFD -> "POPFD"
  | POPFQ -> "POPFQ"
  | POR -> "POR"
  | PREFETCH -> "PREFETCH"
  | PREFETCHNTA -> "PREFETCHNTA"
  | PREFETCHT0 -> "PREFETCHT0"
  | PREFETCHT1 -> "PREFETCHT1"
  | PREFETCHT2 -> "PREFETCHT2"
  | PREFETCHW -> "PREFETCHW"
  | PREFETCHWT1 -> "PREFETCHWT1"
  | PSADBW -> "PSADBW"
  | PSHUFB -> "PSHUFB"
  | PSHUFD -> "PSHUFD"
  | PSHUFHW -> "PSHUFHW"
  | PSHUFLW -> "PSHUFLW"
  | PSHUFW -> "PSHUFW"
  | PSIGNB -> "PSIGNB"
  | PSIGND -> "PSIGND"
  | PSIGNW -> "PSIGNW"
  | PSLLD -> "PSLLD"
  | PSLLDQ -> "PSLLDQ"
  | PSLLQ -> "PSLLQ"
  | PSLLW -> "PSLLW"
  | PSRAD -> "PSRAD"
  | PSRAW -> "PSRAW"
  | PSRLD -> "PSRLD"
  | PSRLDQ -> "PSRLDQ"
  | PSRLQ -> "PSRLQ"
  | PSRLW -> "PSRLW"
  | PSUBB -> "PSUBB"
  | PSUBD -> "PSUBD"
  | PSUBQ -> "PSUBQ"
  | PSUBSB -> "PSUBSB"
  | PSUBSW -> "PSUBSW"
  | PSUBUSB -> "PSUBUSB"
  | PSUBUSW -> "PSUBUSW"
  | PSUBW -> "PSUBW"
  | PSWAPD -> "PSWAPD"
  | PTEST -> "PTEST"
  | PTWRITE -> "PTWRITE"
  | PUNPCKHBW -> "PUNPCKHBW"
  | PUNPCKHDQ -> "PUNPCKHDQ"
  | PUNPCKHQDQ -> "PUNPCKHQDQ"
  | PUNPCKHWD -> "PUNPCKHWD"
  | PUNPCKLBW -> "PUNPCKLBW"
  | PUNPCKLDQ -> "PUNPCKLDQ"
  | PUNPCKLQDQ -> "PUNPCKLQDQ"
  | PUNPCKLWD -> "PUNPCKLWD"
  | PUSH -> "PUSH"
  | PUSHA -> "PUSHA"
  | PUSHAD -> "PUSHAD"
  | PUSHF -> "PUSHF"
  | PUSHFD -> "PUSHFD"
  | PUSHFQ -> "PUSHFQ"
  | PXOR -> "PXOR"
  | RCL -> "RCL"
  | RCPPS -> "RCPPS"
  | RCPSS -> "RCPSS"
  | RCR -> "RCR"
  | RDFSBASE -> "RDFSBASE"
  | RDGSBASE -> "RDGSBASE"
  | RDMSR -> "RDMSR"
  | RDPID -> "RDPID"
  | RDPKRU -> "RDPKRU"
  | RDPMC -> "RDPMC"
  | RDPRU -> "RDPRU"
  | RDRAND -> "RDRAND"
  | RDSEED -> "RDSEED"
  | RDSSPD -> "RDSSPD"
  | RDSSPQ -> "RDSSPQ"
  | RDTSC -> "RDTSC"
  | RDTSCP -> "RDTSCP"
  | RET -> "RET"
  | ROL -> "ROL"
  | ROR -> "ROR"
  | RORX -> "RORX"
  | ROUNDPD -> "ROUNDPD"
  | ROUNDPS -> "ROUNDPS"
  | ROUNDSD -> "ROUNDSD"
  | ROUNDSS -> "ROUNDSS"
  | RSM -> "RSM"
  | RSQRTPS -> "RSQRTPS"
  | RSQRTSS -> "RSQRTSS"
  | RSTORSSP -> "RSTORSSP"
  | SAHF -> "SAHF"
  | SALC -> "SALC"
  | SAR -> "SAR"
  | SARX -> "SARX"
  | SAVEPREVSSP -> "SAVEPREVSSP"
  | SBB -> "SBB"
  | SCASB -> "SCASB"
  | SCASD -> "SCASD"
  | SCASQ -> "SCASQ"
  | SCASW -> "SCASW"
  | SETB -> "SETB"
  | SETBE -> "SETBE"
  | SETL -> "SETL"
  | SETLE -> "SETLE"
  | SETNB -> "SETNB"
  | SETNBE -> "SETNBE"
  | SETNL -> "SETNL"
  | SETNLE -> "SETNLE"
  | SETNO -> "SETNO"
  | SETNP -> "SETNP"
  | SETNS -> "SETNS"
  | SETNZ -> "SETNZ"
  | SETO -> "SETO"
  | SETP -> "SETP"
  | SETS -> "SETS"
  | SETSSBSY -> "SETSSBSY"
  | SETZ -> "SETZ"
  | SFENCE -> "SFENCE"
  | SGDT -> "SGDT"
  | SHA1MSG1 -> "SHA1MSG1"
  | SHA1MSG2 -> "SHA1MSG2"
  | SHA1NEXTE -> "SHA1NEXTE"
  | SHA1RNDS4 -> "SHA1RNDS4"
  | SHA256MSG1 -> "SHA256MSG1"
  | SHA256MSG2 -> "SHA256MSG2"
  | SHA256RNDS2 -> "SHA256RNDS2"
  | SHL -> "SHL"
  | SHLD -> "SHLD"
  | SHLX -> "SHLX"
  | SHR -> "SHR"
  | SHRD -> "SHRD"
  | SHRX -> "SHRX"
  | SHUFPD -> "SHUFPD"
  | SHUFPS -> "SHUFPS"
  | SIDT -> "SIDT"
  | SKINIT -> "SKINIT"
  | SLDT -> "SLDT"
  | SLWPCB -> "SLWPCB"
  | SMSW -> "SMSW"
  | SPFLT -> "SPFLT"
  | SQRTPD -> "SQRTPD"
  | SQRTPS -> "SQRTPS"
  | SQRTSD -> "SQRTSD"
  | SQRTSS -> "SQRTSS"
  | STAC -> "STAC"
  | STC -> "STC"
  | STD -> "STD"
  | STGI -> "STGI"
  | STI -> "STI"
  | STMXCSR -> "STMXCSR"
  | STOSB -> "STOSB"
  | STOSD -> "STOSD"
  | STOSQ -> "STOSQ"
  | STOSW -> "STOSW"
  | STR -> "STR"
  | SUB -> "SUB"
  | SUBPD -> "SUBPD"
  | SUBPS -> "SUBPS"
  | SUBSD -> "SUBSD"
  | SUBSS -> "SUBSS"
  | SWAPGS -> "SWAPGS"
  | SYSCALL -> "SYSCALL"
  | SYSENTER -> "SYSENTER"
  | SYSEXIT -> "SYSEXIT"
  | SYSRET -> "SYSRET"
  | T1MSKC -> "T1MSKC"
  | TEST -> "TEST"
  | TPAUSE -> "TPAUSE"
  | TZCNT -> "TZCNT"
  | TZCNTI -> "TZCNTI"
  | TZMSK -> "TZMSK"
  | UCOMISD -> "UCOMISD"
  | UCOMISS -> "UCOMISS"
  | UD0 -> "UD0"
  | UD1 -> "UD1"
  | UD2 -> "UD2"
  | UMONITOR -> "UMONITOR"
  | UMWAIT -> "UMWAIT"
  | UNPCKHPD -> "UNPCKHPD"
  | UNPCKHPS -> "UNPCKHPS"
  | UNPCKLPD -> "UNPCKLPD"
  | UNPCKLPS -> "UNPCKLPS"
  | V4FMADDPS -> "V4FMADDPS"
  | V4FMADDSS -> "V4FMADDSS"
  | V4FNMADDPS -> "V4FNMADDPS"
  | V4FNMADDSS -> "V4FNMADDSS"
  | VADDNPD -> "VADDNPD"
  | VADDNPS -> "VADDNPS"
  | VADDPD -> "VADDPD"
  | VADDPS -> "VADDPS"
  | VADDSD -> "VADDSD"
  | VADDSETSPS -> "VADDSETSPS"
  | VADDSS -> "VADDSS"
  | VADDSUBPD -> "VADDSUBPD"
  | VADDSUBPS -> "VADDSUBPS"
  | VAESDEC -> "VAESDEC"
  | VAESDECLAST -> "VAESDECLAST"
  | VAESENC -> "VAESENC"
  | VAESENCLAST -> "VAESENCLAST"
  | VAESIMC -> "VAESIMC"
  | VAESKEYGENASSIST -> "VAESKEYGENASSIST"
  | VALIGND -> "VALIGND"
  | VALIGNQ -> "VALIGNQ"
  | VANDNPD -> "VANDNPD"
  | VANDNPS -> "VANDNPS"
  | VANDPD -> "VANDPD"
  | VANDPS -> "VANDPS"
  | VBLENDMPD -> "VBLENDMPD"
  | VBLENDMPS -> "VBLENDMPS"
  | VBLENDPD -> "VBLENDPD"
  | VBLENDPS -> "VBLENDPS"
  | VBLENDVPD -> "VBLENDVPD"
  | VBLENDVPS -> "VBLENDVPS"
  | VBROADCASTF128 -> "VBROADCASTF128"
  | VBROADCASTF32X2 -> "VBROADCASTF32X2"
  | VBROADCASTF32X4 -> "VBROADCASTF32X4"
  | VBROADCASTF32X8 -> "VBROADCASTF32X8"
  | VBROADCASTF64X2 -> "VBROADCASTF64X2"
  | VBROADCASTF64X4 -> "VBROADCASTF64X4"
  | VBROADCASTI128 -> "VBROADCASTI128"
  | VBROADCASTI32X2 -> "VBROADCASTI32X2"
  | VBROADCASTI32X4 -> "VBROADCASTI32X4"
  | VBROADCASTI32X8 -> "VBROADCASTI32X8"
  | VBROADCASTI64X2 -> "VBROADCASTI64X2"
  | VBROADCASTI64X4 -> "VBROADCASTI64X4"
  | VBROADCASTSD -> "VBROADCASTSD"
  | VBROADCASTSS -> "VBROADCASTSS"
  | VCMPPD -> "VCMPPD"
  | VCMPPS -> "VCMPPS"
  | VCMPSD -> "VCMPSD"
  | VCMPSS -> "VCMPSS"
  | VCOMISD -> "VCOMISD"
  | VCOMISS -> "VCOMISS"
  | VCOMPRESSPD -> "VCOMPRESSPD"
  | VCOMPRESSPS -> "VCOMPRESSPS"
  | VCVTDQ2PD -> "VCVTDQ2PD"
  | VCVTDQ2PS -> "VCVTDQ2PS"
  | VCVTFXPNTDQ2PS -> "VCVTFXPNTDQ2PS"
  | VCVTFXPNTPD2DQ -> "VCVTFXPNTPD2DQ"
  | VCVTFXPNTPD2UDQ -> "VCVTFXPNTPD2UDQ"
  | VCVTFXPNTPS2DQ -> "VCVTFXPNTPS2DQ"
  | VCVTFXPNTPS2UDQ -> "VCVTFXPNTPS2UDQ"
  | VCVTFXPNTUDQ2PS -> "VCVTFXPNTUDQ2PS"
  | VCVTNE2PS2BF16 -> "VCVTNE2PS2BF16"
  | VCVTNEPS2BF16 -> "VCVTNEPS2BF16"
  | VCVTPD2DQ -> "VCVTPD2DQ"
  | VCVTPD2PS -> "VCVTPD2PS"
  | VCVTPD2QQ -> "VCVTPD2QQ"
  | VCVTPD2UDQ -> "VCVTPD2UDQ"
  | VCVTPD2UQQ -> "VCVTPD2UQQ"
  | VCVTPH2PS -> "VCVTPH2PS"
  | VCVTPS2DQ -> "VCVTPS2DQ"
  | VCVTPS2PD -> "VCVTPS2PD"
  | VCVTPS2PH -> "VCVTPS2PH"
  | VCVTPS2QQ -> "VCVTPS2QQ"
  | VCVTPS2UDQ -> "VCVTPS2UDQ"
  | VCVTPS2UQQ -> "VCVTPS2UQQ"
  | VCVTQQ2PD -> "VCVTQQ2PD"
  | VCVTQQ2PS -> "VCVTQQ2PS"
  | VCVTSD2SI -> "VCVTSD2SI"
  | VCVTSD2SS -> "VCVTSD2SS"
  | VCVTSD2USI -> "VCVTSD2USI"
  | VCVTSI2SD -> "VCVTSI2SD"
  | VCVTSI2SS -> "VCVTSI2SS"
  | VCVTSS2SD -> "VCVTSS2SD"
  | VCVTSS2SI -> "VCVTSS2SI"
  | VCVTSS2USI -> "VCVTSS2USI"
  | VCVTTPD2DQ -> "VCVTTPD2DQ"
  | VCVTTPD2QQ -> "VCVTTPD2QQ"
  | VCVTTPD2UDQ -> "VCVTTPD2UDQ"
  | VCVTTPD2UQQ -> "VCVTTPD2UQQ"
  | VCVTTPS2DQ -> "VCVTTPS2DQ"
  | VCVTTPS2QQ -> "VCVTTPS2QQ"
  | VCVTTPS2UDQ -> "VCVTTPS2UDQ"
  | VCVTTPS2UQQ -> "VCVTTPS2UQQ"
  | VCVTTSD2SI -> "VCVTTSD2SI"
  | VCVTTSD2USI -> "VCVTTSD2USI"
  | VCVTTSS2SI -> "VCVTTSS2SI"
  | VCVTTSS2USI -> "VCVTTSS2USI"
  | VCVTUDQ2PD -> "VCVTUDQ2PD"
  | VCVTUDQ2PS -> "VCVTUDQ2PS"
  | VCVTUQQ2PD -> "VCVTUQQ2PD"
  | VCVTUQQ2PS -> "VCVTUQQ2PS"
  | VCVTUSI2SD -> "VCVTUSI2SD"
  | VCVTUSI2SS -> "VCVTUSI2SS"
  | VDBPSADBW -> "VDBPSADBW"
  | VDIVPD -> "VDIVPD"
  | VDIVPS -> "VDIVPS"
  | VDIVSD -> "VDIVSD"
  | VDIVSS -> "VDIVSS"
  | VDPBF16PS -> "VDPBF16PS"
  | VDPPD -> "VDPPD"
  | VDPPS -> "VDPPS"
  | VERR -> "VERR"
  | VERW -> "VERW"
  | VEXP223PS -> "VEXP223PS"
  | VEXP2PD -> "VEXP2PD"
  | VEXP2PS -> "VEXP2PS"
  | VEXPANDPD -> "VEXPANDPD"
  | VEXPANDPS -> "VEXPANDPS"
  | VEXTRACTF128 -> "VEXTRACTF128"
  | VEXTRACTF32X4 -> "VEXTRACTF32X4"
  | VEXTRACTF32X8 -> "VEXTRACTF32X8"
  | VEXTRACTF64X2 -> "VEXTRACTF64X2"
  | VEXTRACTF64X4 -> "VEXTRACTF64X4"
  | VEXTRACTI128 -> "VEXTRACTI128"
  | VEXTRACTI32X4 -> "VEXTRACTI32X4"
  | VEXTRACTI32X8 -> "VEXTRACTI32X8"
  | VEXTRACTI64X2 -> "VEXTRACTI64X2"
  | VEXTRACTI64X4 -> "VEXTRACTI64X4"
  | VEXTRACTPS -> "VEXTRACTPS"
  | VFIXUPIMMPD -> "VFIXUPIMMPD"
  | VFIXUPIMMPS -> "VFIXUPIMMPS"
  | VFIXUPIMMSD -> "VFIXUPIMMSD"
  | VFIXUPIMMSS -> "VFIXUPIMMSS"
  | VFIXUPNANPD -> "VFIXUPNANPD"
  | VFIXUPNANPS -> "VFIXUPNANPS"
  | VFMADD132PD -> "VFMADD132PD"
  | VFMADD132PS -> "VFMADD132PS"
  | VFMADD132SD -> "VFMADD132SD"
  | VFMADD132SS -> "VFMADD132SS"
  | VFMADD213PD -> "VFMADD213PD"
  | VFMADD213PS -> "VFMADD213PS"
  | VFMADD213SD -> "VFMADD213SD"
  | VFMADD213SS -> "VFMADD213SS"
  | VFMADD231PD -> "VFMADD231PD"
  | VFMADD231PS -> "VFMADD231PS"
  | VFMADD231SD -> "VFMADD231SD"
  | VFMADD231SS -> "VFMADD231SS"
  | VFMADD233PS -> "VFMADD233PS"
  | VFMADDPD -> "VFMADDPD"
  | VFMADDPS -> "VFMADDPS"
  | VFMADDSD -> "VFMADDSD"
  | VFMADDSS -> "VFMADDSS"
  | VFMADDSUB132PD -> "VFMADDSUB132PD"
  | VFMADDSUB132PS -> "VFMADDSUB132PS"
  | VFMADDSUB213PD -> "VFMADDSUB213PD"
  | VFMADDSUB213PS -> "VFMADDSUB213PS"
  | VFMADDSUB231PD -> "VFMADDSUB231PD"
  | VFMADDSUB231PS -> "VFMADDSUB231PS"
  | VFMADDSUBPD -> "VFMADDSUBPD"
  | VFMADDSUBPS -> "VFMADDSUBPS"
  | VFMSUB132PD -> "VFMSUB132PD"
  | VFMSUB132PS -> "VFMSUB132PS"
  | VFMSUB132SD -> "VFMSUB132SD"
  | VFMSUB132SS -> "VFMSUB132SS"
  | VFMSUB213PD -> "VFMSUB213PD"
  | VFMSUB213PS -> "VFMSUB213PS"
  | VFMSUB213SD -> "VFMSUB213SD"
  | VFMSUB213SS -> "VFMSUB213SS"
  | VFMSUB231PD -> "VFMSUB231PD"
  | VFMSUB231PS -> "VFMSUB231PS"
  | VFMSUB231SD -> "VFMSUB231SD"
  | VFMSUB231SS -> "VFMSUB231SS"
  | VFMSUBADD132PD -> "VFMSUBADD132PD"
  | VFMSUBADD132PS -> "VFMSUBADD132PS"
  | VFMSUBADD213PD -> "VFMSUBADD213PD"
  | VFMSUBADD213PS -> "VFMSUBADD213PS"
  | VFMSUBADD231PD -> "VFMSUBADD231PD"
  | VFMSUBADD231PS -> "VFMSUBADD231PS"
  | VFMSUBADDPD -> "VFMSUBADDPD"
  | VFMSUBADDPS -> "VFMSUBADDPS"
  | VFMSUBPD -> "VFMSUBPD"
  | VFMSUBPS -> "VFMSUBPS"
  | VFMSUBSD -> "VFMSUBSD"
  | VFMSUBSS -> "VFMSUBSS"
  | VFNMADD132PD -> "VFNMADD132PD"
  | VFNMADD132PS -> "VFNMADD132PS"
  | VFNMADD132SD -> "VFNMADD132SD"
  | VFNMADD132SS -> "VFNMADD132SS"
  | VFNMADD213PD -> "VFNMADD213PD"
  | VFNMADD213PS -> "VFNMADD213PS"
  | VFNMADD213SD -> "VFNMADD213SD"
  | VFNMADD213SS -> "VFNMADD213SS"
  | VFNMADD231PD -> "VFNMADD231PD"
  | VFNMADD231PS -> "VFNMADD231PS"
  | VFNMADD231SD -> "VFNMADD231SD"
  | VFNMADD231SS -> "VFNMADD231SS"
  | VFNMADDPD -> "VFNMADDPD"
  | VFNMADDPS -> "VFNMADDPS"
  | VFNMADDSD -> "VFNMADDSD"
  | VFNMADDSS -> "VFNMADDSS"
  | VFNMSUB132PD -> "VFNMSUB132PD"
  | VFNMSUB132PS -> "VFNMSUB132PS"
  | VFNMSUB132SD -> "VFNMSUB132SD"
  | VFNMSUB132SS -> "VFNMSUB132SS"
  | VFNMSUB213PD -> "VFNMSUB213PD"
  | VFNMSUB213PS -> "VFNMSUB213PS"
  | VFNMSUB213SD -> "VFNMSUB213SD"
  | VFNMSUB213SS -> "VFNMSUB213SS"
  | VFNMSUB231PD -> "VFNMSUB231PD"
  | VFNMSUB231PS -> "VFNMSUB231PS"
  | VFNMSUB231SD -> "VFNMSUB231SD"
  | VFNMSUB231SS -> "VFNMSUB231SS"
  | VFNMSUBPD -> "VFNMSUBPD"
  | VFNMSUBPS -> "VFNMSUBPS"
  | VFNMSUBSD -> "VFNMSUBSD"
  | VFNMSUBSS -> "VFNMSUBSS"
  | VFPCLASSPD -> "VFPCLASSPD"
  | VFPCLASSPS -> "VFPCLASSPS"
  | VFPCLASSSD -> "VFPCLASSSD"
  | VFPCLASSSS -> "VFPCLASSSS"
  | VFRCZPD -> "VFRCZPD"
  | VFRCZPS -> "VFRCZPS"
  | VFRCZSD -> "VFRCZSD"
  | VFRCZSS -> "VFRCZSS"
  | VGATHERDPD -> "VGATHERDPD"
  | VGATHERDPS -> "VGATHERDPS"
  | VGATHERPF0DPD -> "VGATHERPF0DPD"
  | VGATHERPF0DPS -> "VGATHERPF0DPS"
  | VGATHERPF0HINTDPD -> "VGATHERPF0HINTDPD"
  | VGATHERPF0HINTDPS -> "VGATHERPF0HINTDPS"
  | VGATHERPF0QPD -> "VGATHERPF0QPD"
  | VGATHERPF0QPS -> "VGATHERPF0QPS"
  | VGATHERPF1DPD -> "VGATHERPF1DPD"
  | VGATHERPF1DPS -> "VGATHERPF1DPS"
  | VGATHERPF1QPD -> "VGATHERPF1QPD"
  | VGATHERPF1QPS -> "VGATHERPF1QPS"
  | VGATHERQPD -> "VGATHERQPD"
  | VGATHERQPS -> "VGATHERQPS"
  | VGETEXPPD -> "VGETEXPPD"
  | VGETEXPPS -> "VGETEXPPS"
  | VGETEXPSD -> "VGETEXPSD"
  | VGETEXPSS -> "VGETEXPSS"
  | VGETMANTPD -> "VGETMANTPD"
  | VGETMANTPS -> "VGETMANTPS"
  | VGETMANTSD -> "VGETMANTSD"
  | VGETMANTSS -> "VGETMANTSS"
  | VGF2P8AFFINEINVQB -> "VGF2P8AFFINEINVQB"
  | VGF2P8AFFINEQB -> "VGF2P8AFFINEQB"
  | VGF2P8MULB -> "VGF2P8MULB"
  | VGMAXABSPS -> "VGMAXABSPS"
  | VGMAXPD -> "VGMAXPD"
  | VGMAXPS -> "VGMAXPS"
  | VGMINPD -> "VGMINPD"
  | VGMINPS -> "VGMINPS"
  | VHADDPD -> "VHADDPD"
  | VHADDPS -> "VHADDPS"
  | VHSUBPD -> "VHSUBPD"
  | VHSUBPS -> "VHSUBPS"
  | VINSERTF128 -> "VINSERTF128"
  | VINSERTF32X4 -> "VINSERTF32X4"
  | VINSERTF32X8 -> "VINSERTF32X8"
  | VINSERTF64X2 -> "VINSERTF64X2"
  | VINSERTF64X4 -> "VINSERTF64X4"
  | VINSERTI128 -> "VINSERTI128"
  | VINSERTI32X4 -> "VINSERTI32X4"
  | VINSERTI32X8 -> "VINSERTI32X8"
  | VINSERTI64X2 -> "VINSERTI64X2"
  | VINSERTI64X4 -> "VINSERTI64X4"
  | VINSERTPS -> "VINSERTPS"
  | VLDDQU -> "VLDDQU"
  | VLDMXCSR -> "VLDMXCSR"
  | VLOADUNPACKHD -> "VLOADUNPACKHD"
  | VLOADUNPACKHPD -> "VLOADUNPACKHPD"
  | VLOADUNPACKHPS -> "VLOADUNPACKHPS"
  | VLOADUNPACKHQ -> "VLOADUNPACKHQ"
  | VLOADUNPACKLD -> "VLOADUNPACKLD"
  | VLOADUNPACKLPD -> "VLOADUNPACKLPD"
  | VLOADUNPACKLPS -> "VLOADUNPACKLPS"
  | VLOADUNPACKLQ -> "VLOADUNPACKLQ"
  | VLOG2PS -> "VLOG2PS"
  | VMASKMOVDQU -> "VMASKMOVDQU"
  | VMASKMOVPD -> "VMASKMOVPD"
  | VMASKMOVPS -> "VMASKMOVPS"
  | VMAXPD -> "VMAXPD"
  | VMAXPS -> "VMAXPS"
  | VMAXSD -> "VMAXSD"
  | VMAXSS -> "VMAXSS"
  | VMCALL -> "VMCALL"
  | VMCLEAR -> "VMCLEAR"
  | VMFUNC -> "VMFUNC"
  | VMINPD -> "VMINPD"
  | VMINPS -> "VMINPS"
  | VMINSD -> "VMINSD"
  | VMINSS -> "VMINSS"
  | VMLAUNCH -> "VMLAUNCH"
  | VMLOAD -> "VMLOAD"
  | VMMCALL -> "VMMCALL"
  | VMOVAPD -> "VMOVAPD"
  | VMOVAPS -> "VMOVAPS"
  | VMOVD -> "VMOVD"
  | VMOVDDUP -> "VMOVDDUP"
  | VMOVDQA -> "VMOVDQA"
  | VMOVDQA32 -> "VMOVDQA32"
  | VMOVDQA64 -> "VMOVDQA64"
  | VMOVDQU -> "VMOVDQU"
  | VMOVDQU16 -> "VMOVDQU16"
  | VMOVDQU32 -> "VMOVDQU32"
  | VMOVDQU64 -> "VMOVDQU64"
  | VMOVDQU8 -> "VMOVDQU8"
  | VMOVHLPS -> "VMOVHLPS"
  | VMOVHPD -> "VMOVHPD"
  | VMOVHPS -> "VMOVHPS"
  | VMOVLHPS -> "VMOVLHPS"
  | VMOVLPD -> "VMOVLPD"
  | VMOVLPS -> "VMOVLPS"
  | VMOVMSKPD -> "VMOVMSKPD"
  | VMOVMSKPS -> "VMOVMSKPS"
  | VMOVNRAPD -> "VMOVNRAPD"
  | VMOVNRAPS -> "VMOVNRAPS"
  | VMOVNRNGOAPD -> "VMOVNRNGOAPD"
  | VMOVNRNGOAPS -> "VMOVNRNGOAPS"
  | VMOVNTDQ -> "VMOVNTDQ"
  | VMOVNTDQA -> "VMOVNTDQA"
  | VMOVNTPD -> "VMOVNTPD"
  | VMOVNTPS -> "VMOVNTPS"
  | VMOVQ -> "VMOVQ"
  | VMOVSD -> "VMOVSD"
  | VMOVSHDUP -> "VMOVSHDUP"
  | VMOVSLDUP -> "VMOVSLDUP"
  | VMOVSS -> "VMOVSS"
  | VMOVUPD -> "VMOVUPD"
  | VMOVUPS -> "VMOVUPS"
  | VMPSADBW -> "VMPSADBW"
  | VMPTRLD -> "VMPTRLD"
  | VMPTRST -> "VMPTRST"
  | VMREAD -> "VMREAD"
  | VMRESUME -> "VMRESUME"
  | VMRUN -> "VMRUN"
  | VMSAVE -> "VMSAVE"
  | VMULPD -> "VMULPD"
  | VMULPS -> "VMULPS"
  | VMULSD -> "VMULSD"
  | VMULSS -> "VMULSS"
  | VMWRITE -> "VMWRITE"
  | VMXOFF -> "VMXOFF"
  | VMXON -> "VMXON"
  | VORPD -> "VORPD"
  | VORPS -> "VORPS"
  | VP2INTERSECTD -> "VP2INTERSECTD"
  | VP2INTERSECTQ -> "VP2INTERSECTQ"
  | VP4DPWSSD -> "VP4DPWSSD"
  | VP4DPWSSDS -> "VP4DPWSSDS"
  | VPABSB -> "VPABSB"
  | VPABSD -> "VPABSD"
  | VPABSQ -> "VPABSQ"
  | VPABSW -> "VPABSW"
  | VPACKSSDW -> "VPACKSSDW"
  | VPACKSSWB -> "VPACKSSWB"
  | VPACKSTOREHD -> "VPACKSTOREHD"
  | VPACKSTOREHPD -> "VPACKSTOREHPD"
  | VPACKSTOREHPS -> "VPACKSTOREHPS"
  | VPACKSTOREHQ -> "VPACKSTOREHQ"
  | VPACKSTORELD -> "VPACKSTORELD"
  | VPACKSTORELPD -> "VPACKSTORELPD"
  | VPACKSTORELPS -> "VPACKSTORELPS"
  | VPACKSTORELQ -> "VPACKSTORELQ"
  | VPACKUSDW -> "VPACKUSDW"
  | VPACKUSWB -> "VPACKUSWB"
  | VPADCD -> "VPADCD"
  | VPADDB -> "VPADDB"
  | VPADDD -> "VPADDD"
  | VPADDQ -> "VPADDQ"
  | VPADDSB -> "VPADDSB"
  | VPADDSETCD -> "VPADDSETCD"
  | VPADDSETSD -> "VPADDSETSD"
  | VPADDSW -> "VPADDSW"
  | VPADDUSB -> "VPADDUSB"
  | VPADDUSW -> "VPADDUSW"
  | VPADDW -> "VPADDW"
  | VPALIGNR -> "VPALIGNR"
  | VPAND -> "VPAND"
  | VPANDD -> "VPANDD"
  | VPANDN -> "VPANDN"
  | VPANDND -> "VPANDND"
  | VPANDNQ -> "VPANDNQ"
  | VPANDQ -> "VPANDQ"
  | VPAVGB -> "VPAVGB"
  | VPAVGW -> "VPAVGW"
  | VPBLENDD -> "VPBLENDD"
  | VPBLENDMB -> "VPBLENDMB"
  | VPBLENDMD -> "VPBLENDMD"
  | VPBLENDMQ -> "VPBLENDMQ"
  | VPBLENDMW -> "VPBLENDMW"
  | VPBLENDVB -> "VPBLENDVB"
  | VPBLENDW -> "VPBLENDW"
  | VPBROADCASTB -> "VPBROADCASTB"
  | VPBROADCASTD -> "VPBROADCASTD"
  | VPBROADCASTMB2Q -> "VPBROADCASTMB2Q"
  | VPBROADCASTMW2D -> "VPBROADCASTMW2D"
  | VPBROADCASTQ -> "VPBROADCASTQ"
  | VPBROADCASTW -> "VPBROADCASTW"
  | VPCLMULQDQ -> "VPCLMULQDQ"
  | VPCMOV -> "VPCMOV"
  | VPCMPB -> "VPCMPB"
  | VPCMPD -> "VPCMPD"
  | VPCMPEQB -> "VPCMPEQB"
  | VPCMPEQD -> "VPCMPEQD"
  | VPCMPEQQ -> "VPCMPEQQ"
  | VPCMPEQW -> "VPCMPEQW"
  | VPCMPESTRI -> "VPCMPESTRI"
  | VPCMPESTRM -> "VPCMPESTRM"
  | VPCMPGTB -> "VPCMPGTB"
  | VPCMPGTD -> "VPCMPGTD"
  | VPCMPGTQ -> "VPCMPGTQ"
  | VPCMPGTW -> "VPCMPGTW"
  | VPCMPISTRI -> "VPCMPISTRI"
  | VPCMPISTRM -> "VPCMPISTRM"
  | VPCMPLTD -> "VPCMPLTD"
  | VPCMPQ -> "VPCMPQ"
  | VPCMPUB -> "VPCMPUB"
  | VPCMPUD -> "VPCMPUD"
  | VPCMPUQ -> "VPCMPUQ"
  | VPCMPUW -> "VPCMPUW"
  | VPCMPW -> "VPCMPW"
  | VPCOMB -> "VPCOMB"
  | VPCOMD -> "VPCOMD"
  | VPCOMPRESSB -> "VPCOMPRESSB"
  | VPCOMPRESSD -> "VPCOMPRESSD"
  | VPCOMPRESSQ -> "VPCOMPRESSQ"
  | VPCOMPRESSW -> "VPCOMPRESSW"
  | VPCOMQ -> "VPCOMQ"
  | VPCOMUB -> "VPCOMUB"
  | VPCOMUD -> "VPCOMUD"
  | VPCOMUQ -> "VPCOMUQ"
  | VPCOMUW -> "VPCOMUW"
  | VPCOMW -> "VPCOMW"
  | VPCONFLICTD -> "VPCONFLICTD"
  | VPCONFLICTQ -> "VPCONFLICTQ"
  | VPDPBUSD -> "VPDPBUSD"
  | VPDPBUSDS -> "VPDPBUSDS"
  | VPDPWSSD -> "VPDPWSSD"
  | VPDPWSSDS -> "VPDPWSSDS"
  | VPERM2F128 -> "VPERM2F128"
  | VPERM2I128 -> "VPERM2I128"
  | VPERMB -> "VPERMB"
  | VPERMD -> "VPERMD"
  | VPERMF32X4 -> "VPERMF32X4"
  | VPERMI2B -> "VPERMI2B"
  | VPERMI2D -> "VPERMI2D"
  | VPERMI2PD -> "VPERMI2PD"
  | VPERMI2PS -> "VPERMI2PS"
  | VPERMI2Q -> "VPERMI2Q"
  | VPERMI2W -> "VPERMI2W"
  | VPERMIL2PD -> "VPERMIL2PD"
  | VPERMIL2PS -> "VPERMIL2PS"
  | VPERMILPD -> "VPERMILPD"
  | VPERMILPS -> "VPERMILPS"
  | VPERMPD -> "VPERMPD"
  | VPERMPS -> "VPERMPS"
  | VPERMQ -> "VPERMQ"
  | VPERMT2B -> "VPERMT2B"
  | VPERMT2D -> "VPERMT2D"
  | VPERMT2PD -> "VPERMT2PD"
  | VPERMT2PS -> "VPERMT2PS"
  | VPERMT2Q -> "VPERMT2Q"
  | VPERMT2W -> "VPERMT2W"
  | VPERMW -> "VPERMW"
  | VPEXPANDB -> "VPEXPANDB"
  | VPEXPANDD -> "VPEXPANDD"
  | VPEXPANDQ -> "VPEXPANDQ"
  | VPEXPANDW -> "VPEXPANDW"
  | VPEXTRB -> "VPEXTRB"
  | VPEXTRD -> "VPEXTRD"
  | VPEXTRQ -> "VPEXTRQ"
  | VPEXTRW -> "VPEXTRW"
  | VPGATHERDD -> "VPGATHERDD"
  | VPGATHERDQ -> "VPGATHERDQ"
  | VPGATHERQD -> "VPGATHERQD"
  | VPGATHERQQ -> "VPGATHERQQ"
  | VPHADDBD -> "VPHADDBD"
  | VPHADDBQ -> "VPHADDBQ"
  | VPHADDBW -> "VPHADDBW"
  | VPHADDD -> "VPHADDD"
  | VPHADDDQ -> "VPHADDDQ"
  | VPHADDSW -> "VPHADDSW"
  | VPHADDUBD -> "VPHADDUBD"
  | VPHADDUBQ -> "VPHADDUBQ"
  | VPHADDUBW -> "VPHADDUBW"
  | VPHADDUDQ -> "VPHADDUDQ"
  | VPHADDUWD -> "VPHADDUWD"
  | VPHADDUWQ -> "VPHADDUWQ"
  | VPHADDW -> "VPHADDW"
  | VPHADDWD -> "VPHADDWD"
  | VPHADDWQ -> "VPHADDWQ"
  | VPHMINPOSUW -> "VPHMINPOSUW"
  | VPHSUBBW -> "VPHSUBBW"
  | VPHSUBD -> "VPHSUBD"
  | VPHSUBDQ -> "VPHSUBDQ"
  | VPHSUBSW -> "VPHSUBSW"
  | VPHSUBW -> "VPHSUBW"
  | VPHSUBWD -> "VPHSUBWD"
  | VPINSRB -> "VPINSRB"
  | VPINSRD -> "VPINSRD"
  | VPINSRQ -> "VPINSRQ"
  | VPINSRW -> "VPINSRW"
  | VPLZCNTD -> "VPLZCNTD"
  | VPLZCNTQ -> "VPLZCNTQ"
  | VPMACSDD -> "VPMACSDD"
  | VPMACSDQH -> "VPMACSDQH"
  | VPMACSDQL -> "VPMACSDQL"
  | VPMACSSDD -> "VPMACSSDD"
  | VPMACSSDQH -> "VPMACSSDQH"
  | VPMACSSDQL -> "VPMACSSDQL"
  | VPMACSSWD -> "VPMACSSWD"
  | VPMACSSWW -> "VPMACSSWW"
  | VPMACSWD -> "VPMACSWD"
  | VPMACSWW -> "VPMACSWW"
  | VPMADCSSWD -> "VPMADCSSWD"
  | VPMADCSWD -> "VPMADCSWD"
  | VPMADD231D -> "VPMADD231D"
  | VPMADD233D -> "VPMADD233D"
  | VPMADD52HUQ -> "VPMADD52HUQ"
  | VPMADD52LUQ -> "VPMADD52LUQ"
  | VPMADDUBSW -> "VPMADDUBSW"
  | VPMADDWD -> "VPMADDWD"
  | VPMASKMOVD -> "VPMASKMOVD"
  | VPMASKMOVQ -> "VPMASKMOVQ"
  | VPMAXSB -> "VPMAXSB"
  | VPMAXSD -> "VPMAXSD"
  | VPMAXSQ -> "VPMAXSQ"
  | VPMAXSW -> "VPMAXSW"
  | VPMAXUB -> "VPMAXUB"
  | VPMAXUD -> "VPMAXUD"
  | VPMAXUQ -> "VPMAXUQ"
  | VPMAXUW -> "VPMAXUW"
  | VPMINSB -> "VPMINSB"
  | VPMINSD -> "VPMINSD"
  | VPMINSQ -> "VPMINSQ"
  | VPMINSW -> "VPMINSW"
  | VPMINUB -> "VPMINUB"
  | VPMINUD -> "VPMINUD"
  | VPMINUQ -> "VPMINUQ"
  | VPMINUW -> "VPMINUW"
  | VPMOVB2M -> "VPMOVB2M"
  | VPMOVD2M -> "VPMOVD2M"
  | VPMOVDB -> "VPMOVDB"
  | VPMOVDW -> "VPMOVDW"
  | VPMOVM2B -> "VPMOVM2B"
  | VPMOVM2D -> "VPMOVM2D"
  | VPMOVM2Q -> "VPMOVM2Q"
  | VPMOVM2W -> "VPMOVM2W"
  | VPMOVMSKB -> "VPMOVMSKB"
  | VPMOVQ2M -> "VPMOVQ2M"
  | VPMOVQB -> "VPMOVQB"
  | VPMOVQD -> "VPMOVQD"
  | VPMOVQW -> "VPMOVQW"
  | VPMOVSDB -> "VPMOVSDB"
  | VPMOVSDW -> "VPMOVSDW"
  | VPMOVSQB -> "VPMOVSQB"
  | VPMOVSQD -> "VPMOVSQD"
  | VPMOVSQW -> "VPMOVSQW"
  | VPMOVSWB -> "VPMOVSWB"
  | VPMOVSXBD -> "VPMOVSXBD"
  | VPMOVSXBQ -> "VPMOVSXBQ"
  | VPMOVSXBW -> "VPMOVSXBW"
  | VPMOVSXDQ -> "VPMOVSXDQ"
  | VPMOVSXWD -> "VPMOVSXWD"
  | VPMOVSXWQ -> "VPMOVSXWQ"
  | VPMOVUSDB -> "VPMOVUSDB"
  | VPMOVUSDW -> "VPMOVUSDW"
  | VPMOVUSQB -> "VPMOVUSQB"
  | VPMOVUSQD -> "VPMOVUSQD"
  | VPMOVUSQW -> "VPMOVUSQW"
  | VPMOVUSWB -> "VPMOVUSWB"
  | VPMOVW2M -> "VPMOVW2M"
  | VPMOVWB -> "VPMOVWB"
  | VPMOVZXBD -> "VPMOVZXBD"
  | VPMOVZXBQ -> "VPMOVZXBQ"
  | VPMOVZXBW -> "VPMOVZXBW"
  | VPMOVZXDQ -> "VPMOVZXDQ"
  | VPMOVZXWD -> "VPMOVZXWD"
  | VPMOVZXWQ -> "VPMOVZXWQ"
  | VPMULDQ -> "VPMULDQ"
  | VPMULHD -> "VPMULHD"
  | VPMULHRSW -> "VPMULHRSW"
  | VPMULHUD -> "VPMULHUD"
  | VPMULHUW -> "VPMULHUW"
  | VPMULHW -> "VPMULHW"
  | VPMULLD -> "VPMULLD"
  | VPMULLQ -> "VPMULLQ"
  | VPMULLW -> "VPMULLW"
  | VPMULTISHIFTQB -> "VPMULTISHIFTQB"
  | VPMULUDQ -> "VPMULUDQ"
  | VPOPCNTB -> "VPOPCNTB"
  | VPOPCNTD -> "VPOPCNTD"
  | VPOPCNTQ -> "VPOPCNTQ"
  | VPOPCNTW -> "VPOPCNTW"
  | VPOR -> "VPOR"
  | VPORD -> "VPORD"
  | VPORQ -> "VPORQ"
  | VPPERM -> "VPPERM"
  | VPREFETCH0 -> "VPREFETCH0"
  | VPREFETCH1 -> "VPREFETCH1"
  | VPREFETCH2 -> "VPREFETCH2"
  | VPREFETCHE0 -> "VPREFETCHE0"
  | VPREFETCHE1 -> "VPREFETCHE1"
  | VPREFETCHE2 -> "VPREFETCHE2"
  | VPREFETCHENTA -> "VPREFETCHENTA"
  | VPREFETCHNTA -> "VPREFETCHNTA"
  | VPROLD -> "VPROLD"
  | VPROLQ -> "VPROLQ"
  | VPROLVD -> "VPROLVD"
  | VPROLVQ -> "VPROLVQ"
  | VPRORD -> "VPRORD"
  | VPRORQ -> "VPRORQ"
  | VPRORVD -> "VPRORVD"
  | VPRORVQ -> "VPRORVQ"
  | VPROTB -> "VPROTB"
  | VPROTD -> "VPROTD"
  | VPROTQ -> "VPROTQ"
  | VPROTW -> "VPROTW"
  | VPSADBW -> "VPSADBW"
  | VPSBBD -> "VPSBBD"
  | VPSBBRD -> "VPSBBRD"
  | VPSCATTERDD -> "VPSCATTERDD"
  | VPSCATTERDQ -> "VPSCATTERDQ"
  | VPSCATTERQD -> "VPSCATTERQD"
  | VPSCATTERQQ -> "VPSCATTERQQ"
  | VPSHAB -> "VPSHAB"
  | VPSHAD -> "VPSHAD"
  | VPSHAQ -> "VPSHAQ"
  | VPSHAW -> "VPSHAW"
  | VPSHLB -> "VPSHLB"
  | VPSHLD -> "VPSHLD"
  | VPSHLDD -> "VPSHLDD"
  | VPSHLDQ -> "VPSHLDQ"
  | VPSHLDVD -> "VPSHLDVD"
  | VPSHLDVQ -> "VPSHLDVQ"
  | VPSHLDVW -> "VPSHLDVW"
  | VPSHLDW -> "VPSHLDW"
  | VPSHLQ -> "VPSHLQ"
  | VPSHLW -> "VPSHLW"
  | VPSHRDD -> "VPSHRDD"
  | VPSHRDQ -> "VPSHRDQ"
  | VPSHRDVD -> "VPSHRDVD"
  | VPSHRDVQ -> "VPSHRDVQ"
  | VPSHRDVW -> "VPSHRDVW"
  | VPSHRDW -> "VPSHRDW"
  | VPSHUFB -> "VPSHUFB"
  | VPSHUFBITQMB -> "VPSHUFBITQMB"
  | VPSHUFD -> "VPSHUFD"
  | VPSHUFHW -> "VPSHUFHW"
  | VPSHUFLW -> "VPSHUFLW"
  | VPSIGNB -> "VPSIGNB"
  | VPSIGND -> "VPSIGND"
  | VPSIGNW -> "VPSIGNW"
  | VPSLLD -> "VPSLLD"
  | VPSLLDQ -> "VPSLLDQ"
  | VPSLLQ -> "VPSLLQ"
  | VPSLLVD -> "VPSLLVD"
  | VPSLLVQ -> "VPSLLVQ"
  | VPSLLVW -> "VPSLLVW"
  | VPSLLW -> "VPSLLW"
  | VPSRAD -> "VPSRAD"
  | VPSRAQ -> "VPSRAQ"
  | VPSRAVD -> "VPSRAVD"
  | VPSRAVQ -> "VPSRAVQ"
  | VPSRAVW -> "VPSRAVW"
  | VPSRAW -> "VPSRAW"
  | VPSRLD -> "VPSRLD"
  | VPSRLDQ -> "VPSRLDQ"
  | VPSRLQ -> "VPSRLQ"
  | VPSRLVD -> "VPSRLVD"
  | VPSRLVQ -> "VPSRLVQ"
  | VPSRLVW -> "VPSRLVW"
  | VPSRLW -> "VPSRLW"
  | VPSUBB -> "VPSUBB"
  | VPSUBD -> "VPSUBD"
  | VPSUBQ -> "VPSUBQ"
  | VPSUBRD -> "VPSUBRD"
  | VPSUBRSETBD -> "VPSUBRSETBD"
  | VPSUBSB -> "VPSUBSB"
  | VPSUBSETBD -> "VPSUBSETBD"
  | VPSUBSW -> "VPSUBSW"
  | VPSUBUSB -> "VPSUBUSB"
  | VPSUBUSW -> "VPSUBUSW"
  | VPSUBW -> "VPSUBW"
  | VPTERNLOGD -> "VPTERNLOGD"
  | VPTERNLOGQ -> "VPTERNLOGQ"
  | VPTEST -> "VPTEST"
  | VPTESTMB -> "VPTESTMB"
  | VPTESTMD -> "VPTESTMD"
  | VPTESTMQ -> "VPTESTMQ"
  | VPTESTMW -> "VPTESTMW"
  | VPTESTNMB -> "VPTESTNMB"
  | VPTESTNMD -> "VPTESTNMD"
  | VPTESTNMQ -> "VPTESTNMQ"
  | VPTESTNMW -> "VPTESTNMW"
  | VPUNPCKHBW -> "VPUNPCKHBW"
  | VPUNPCKHDQ -> "VPUNPCKHDQ"
  | VPUNPCKHQDQ -> "VPUNPCKHQDQ"
  | VPUNPCKHWD -> "VPUNPCKHWD"
  | VPUNPCKLBW -> "VPUNPCKLBW"
  | VPUNPCKLDQ -> "VPUNPCKLDQ"
  | VPUNPCKLQDQ -> "VPUNPCKLQDQ"
  | VPUNPCKLWD -> "VPUNPCKLWD"
  | VPXOR -> "VPXOR"
  | VPXORD -> "VPXORD"
  | VPXORQ -> "VPXORQ"
  | VRANGEPD -> "VRANGEPD"
  | VRANGEPS -> "VRANGEPS"
  | VRANGESD -> "VRANGESD"
  | VRANGESS -> "VRANGESS"
  | VRCP14PD -> "VRCP14PD"
  | VRCP14PS -> "VRCP14PS"
  | VRCP14SD -> "VRCP14SD"
  | VRCP14SS -> "VRCP14SS"
  | VRCP23PS -> "VRCP23PS"
  | VRCP28PD -> "VRCP28PD"
  | VRCP28PS -> "VRCP28PS"
  | VRCP28SD -> "VRCP28SD"
  | VRCP28SS -> "VRCP28SS"
  | VRCPPS -> "VRCPPS"
  | VRCPSS -> "VRCPSS"
  | VREDUCEPD -> "VREDUCEPD"
  | VREDUCEPS -> "VREDUCEPS"
  | VREDUCESD -> "VREDUCESD"
  | VREDUCESS -> "VREDUCESS"
  | VRNDFXPNTPD -> "VRNDFXPNTPD"
  | VRNDFXPNTPS -> "VRNDFXPNTPS"
  | VRNDSCALEPD -> "VRNDSCALEPD"
  | VRNDSCALEPS -> "VRNDSCALEPS"
  | VRNDSCALESD -> "VRNDSCALESD"
  | VRNDSCALESS -> "VRNDSCALESS"
  | VROUNDPD -> "VROUNDPD"
  | VROUNDPS -> "VROUNDPS"
  | VROUNDSD -> "VROUNDSD"
  | VROUNDSS -> "VROUNDSS"
  | VRSQRT14PD -> "VRSQRT14PD"
  | VRSQRT14PS -> "VRSQRT14PS"
  | VRSQRT14SD -> "VRSQRT14SD"
  | VRSQRT14SS -> "VRSQRT14SS"
  | VRSQRT23PS -> "VRSQRT23PS"
  | VRSQRT28PD -> "VRSQRT28PD"
  | VRSQRT28PS -> "VRSQRT28PS"
  | VRSQRT28SD -> "VRSQRT28SD"
  | VRSQRT28SS -> "VRSQRT28SS"
  | VRSQRTPS -> "VRSQRTPS"
  | VRSQRTSS -> "VRSQRTSS"
  | VSCALEFPD -> "VSCALEFPD"
  | VSCALEFPS -> "VSCALEFPS"
  | VSCALEFSD -> "VSCALEFSD"
  | VSCALEFSS -> "VSCALEFSS"
  | VSCALEPS -> "VSCALEPS"
  | VSCATTERDPD -> "VSCATTERDPD"
  | VSCATTERDPS -> "VSCATTERDPS"
  | VSCATTERPF0DPD -> "VSCATTERPF0DPD"
  | VSCATTERPF0DPS -> "VSCATTERPF0DPS"
  | VSCATTERPF0HINTDPD -> "VSCATTERPF0HINTDPD"
  | VSCATTERPF0HINTDPS -> "VSCATTERPF0HINTDPS"
  | VSCATTERPF0QPD -> "VSCATTERPF0QPD"
  | VSCATTERPF0QPS -> "VSCATTERPF0QPS"
  | VSCATTERPF1DPD -> "VSCATTERPF1DPD"
  | VSCATTERPF1DPS -> "VSCATTERPF1DPS"
  | VSCATTERPF1QPD -> "VSCATTERPF1QPD"
  | VSCATTERPF1QPS -> "VSCATTERPF1QPS"
  | VSCATTERQPD -> "VSCATTERQPD"
  | VSCATTERQPS -> "VSCATTERQPS"
  | VSHUFF32X4 -> "VSHUFF32X4"
  | VSHUFF64X2 -> "VSHUFF64X2"
  | VSHUFI32X4 -> "VSHUFI32X4"
  | VSHUFI64X2 -> "VSHUFI64X2"
  | VSHUFPD -> "VSHUFPD"
  | VSHUFPS -> "VSHUFPS"
  | VSQRTPD -> "VSQRTPD"
  | VSQRTPS -> "VSQRTPS"
  | VSQRTSD -> "VSQRTSD"
  | VSQRTSS -> "VSQRTSS"
  | VSTMXCSR -> "VSTMXCSR"
  | VSUBPD -> "VSUBPD"
  | VSUBPS -> "VSUBPS"
  | VSUBRPD -> "VSUBRPD"
  | VSUBRPS -> "VSUBRPS"
  | VSUBSD -> "VSUBSD"
  | VSUBSS -> "VSUBSS"
  | VTESTPD -> "VTESTPD"
  | VTESTPS -> "VTESTPS"
  | VUCOMISD -> "VUCOMISD"
  | VUCOMISS -> "VUCOMISS"
  | VUNPCKHPD -> "VUNPCKHPD"
  | VUNPCKHPS -> "VUNPCKHPS"
  | VUNPCKLPD -> "VUNPCKLPD"
  | VUNPCKLPS -> "VUNPCKLPS"
  | VXORPD -> "VXORPD"
  | VXORPS -> "VXORPS"
  | VZEROALL -> "VZEROALL"
  | VZEROUPPER -> "VZEROUPPER"
  | WBINVD -> "WBINVD"
  | WRFSBASE -> "WRFSBASE"
  | WRGSBASE -> "WRGSBASE"
  | WRMSR -> "WRMSR"
  | WRPKRU -> "WRPKRU"
  | WRSSD -> "WRSSD"
  | WRSSQ -> "WRSSQ"
  | WRUSSD -> "WRUSSD"
  | WRUSSQ -> "WRUSSQ"
  | XABORT -> "XABORT"
  | XADD -> "XADD"
  | XBEGIN -> "XBEGIN"
  | XCHG -> "XCHG"
  | XCRYPT_CBC -> "XCRYPT_CBC"
  | XCRYPT_CFB -> "XCRYPT_CFB"
  | XCRYPT_CTR -> "XCRYPT_CTR"
  | XCRYPT_ECB -> "XCRYPT_ECB"
  | XCRYPT_OFB -> "XCRYPT_OFB"
  | XEND -> "XEND"
  | XGETBV -> "XGETBV"
  | XLAT -> "XLAT"
  | XOR -> "XOR"
  | XORPD -> "XORPD"
  | XORPS -> "XORPS"
  | XRSTOR -> "XRSTOR"
  | XRSTOR64 -> "XRSTOR64"
  | XRSTORS -> "XRSTORS"
  | XRSTORS64 -> "XRSTORS64"
  | XSAVE -> "XSAVE"
  | XSAVE64 -> "XSAVE64"
  | XSAVEC -> "XSAVEC"
  | XSAVEC64 -> "XSAVEC64"
  | XSAVEOPT -> "XSAVEOPT"
  | XSAVEOPT64 -> "XSAVEOPT64"
  | XSAVES -> "XSAVES"
  | XSAVES64 -> "XSAVES64"
  | XSETBV -> "XSETBV"
  | XSHA1 -> "XSHA1"
  | XSHA256 -> "XSHA256"
  | XSTORE -> "XSTORE"
  | XTEST -> "XTEST"

let str_of_reg (x:Enums.register) = match x with
  | AL -> "AL"
  | CL -> "CL"
  | DL -> "DL"
  | BL -> "BL"
  | AH -> "AH"
  | CH -> "CH"
  | DH -> "DH"
  | BH -> "BH"
  | SPL -> "SPL"
  | BPL -> "BPL"
  | SIL -> "SIL"
  | DIL -> "DIL"
  | R8B -> "R8B"
  | R9B -> "R9B"
  | R10B -> "R10B"
  | R11B -> "R11B"
  | R12B -> "R12B"
  | R13B -> "R13B"
  | R14B -> "R14B"
  | R15B -> "R15B"
  | AX -> "AX"
  | CX -> "CX"
  | DX -> "DX"
  | BX -> "BX"
  | SP -> "SP"
  | BP -> "BP"
  | SI -> "SI"
  | DI -> "DI"
  | R8W -> "R8W"
  | R9W -> "R9W"
  | R10W -> "R10W"
  | R11W -> "R11W"
  | R12W -> "R12W"
  | R13W -> "R13W"
  | R14W -> "R14W"
  | R15W -> "R15W"
  | EAX -> "EAX"
  | ECX -> "ECX"
  | EDX -> "EDX"
  | EBX -> "EBX"
  | ESP -> "ESP"
  | EBP -> "EBP"
  | ESI -> "ESI"
  | EDI -> "EDI"
  | R8D -> "R8D"
  | R9D -> "R9D"
  | R10D -> "R10D"
  | R11D -> "R11D"
  | R12D -> "R12D"
  | R13D -> "R13D"
  | R14D -> "R14D"
  | R15D -> "R15D"
  | RAX -> "RAX"
  | RCX -> "RCX"
  | RDX -> "RDX"
  | RBX -> "RBX"
  | RSP -> "RSP"
  | RBP -> "RBP"
  | RSI -> "RSI"
  | RDI -> "RDI"
  | R8 -> "R8"
  | R9 -> "R9"
  | R10 -> "R10"
  | R11 -> "R11"
  | R12 -> "R12"
  | R13 -> "R13"
  | R14 -> "R14"
  | R15 -> "R15"
  | ST0 -> "ST0"
  | ST1 -> "ST1"
  | ST2 -> "ST2"
  | ST3 -> "ST3"
  | ST4 -> "ST4"
  | ST5 -> "ST5"
  | ST6 -> "ST6"
  | ST7 -> "ST7"
  | X87CONTROL -> "X87CONTROL"
  | X87STATUS -> "X87STATUS"
  | X87TAG -> "X87TAG"
  | MM0 -> "MM0"
  | MM1 -> "MM1"
  | MM2 -> "MM2"
  | MM3 -> "MM3"
  | MM4 -> "MM4"
  | MM5 -> "MM5"
  | MM6 -> "MM6"
  | MM7 -> "MM7"
  | XMM0 -> "XMM0"
  | XMM1 -> "XMM1"
  | XMM2 -> "XMM2"
  | XMM3 -> "XMM3"
  | XMM4 -> "XMM4"
  | XMM5 -> "XMM5"
  | XMM6 -> "XMM6"
  | XMM7 -> "XMM7"
  | XMM8 -> "XMM8"
  | XMM9 -> "XMM9"
  | XMM10 -> "XMM10"
  | XMM11 -> "XMM11"
  | XMM12 -> "XMM12"
  | XMM13 -> "XMM13"
  | XMM14 -> "XMM14"
  | XMM15 -> "XMM15"
  | XMM16 -> "XMM16"
  | XMM17 -> "XMM17"
  | XMM18 -> "XMM18"
  | XMM19 -> "XMM19"
  | XMM20 -> "XMM20"
  | XMM21 -> "XMM21"
  | XMM22 -> "XMM22"
  | XMM23 -> "XMM23"
  | XMM24 -> "XMM24"
  | XMM25 -> "XMM25"
  | XMM26 -> "XMM26"
  | XMM27 -> "XMM27"
  | XMM28 -> "XMM28"
  | XMM29 -> "XMM29"
  | XMM30 -> "XMM30"
  | XMM31 -> "XMM31"
  | YMM0 -> "YMM0"
  | YMM1 -> "YMM1"
  | YMM2 -> "YMM2"
  | YMM3 -> "YMM3"
  | YMM4 -> "YMM4"
  | YMM5 -> "YMM5"
  | YMM6 -> "YMM6"
  | YMM7 -> "YMM7"
  | YMM8 -> "YMM8"
  | YMM9 -> "YMM9"
  | YMM10 -> "YMM10"
  | YMM11 -> "YMM11"
  | YMM12 -> "YMM12"
  | YMM13 -> "YMM13"
  | YMM14 -> "YMM14"
  | YMM15 -> "YMM15"
  | YMM16 -> "YMM16"
  | YMM17 -> "YMM17"
  | YMM18 -> "YMM18"
  | YMM19 -> "YMM19"
  | YMM20 -> "YMM20"
  | YMM21 -> "YMM21"
  | YMM22 -> "YMM22"
  | YMM23 -> "YMM23"
  | YMM24 -> "YMM24"
  | YMM25 -> "YMM25"
  | YMM26 -> "YMM26"
  | YMM27 -> "YMM27"
  | YMM28 -> "YMM28"
  | YMM29 -> "YMM29"
  | YMM30 -> "YMM30"
  | YMM31 -> "YMM31"
  | ZMM0 -> "ZMM0"
  | ZMM1 -> "ZMM1"
  | ZMM2 -> "ZMM2"
  | ZMM3 -> "ZMM3"
  | ZMM4 -> "ZMM4"
  | ZMM5 -> "ZMM5"
  | ZMM6 -> "ZMM6"
  | ZMM7 -> "ZMM7"
  | ZMM8 -> "ZMM8"
  | ZMM9 -> "ZMM9"
  | ZMM10 -> "ZMM10"
  | ZMM11 -> "ZMM11"
  | ZMM12 -> "ZMM12"
  | ZMM13 -> "ZMM13"
  | ZMM14 -> "ZMM14"
  | ZMM15 -> "ZMM15"
  | ZMM16 -> "ZMM16"
  | ZMM17 -> "ZMM17"
  | ZMM18 -> "ZMM18"
  | ZMM19 -> "ZMM19"
  | ZMM20 -> "ZMM20"
  | ZMM21 -> "ZMM21"
  | ZMM22 -> "ZMM22"
  | ZMM23 -> "ZMM23"
  | ZMM24 -> "ZMM24"
  | ZMM25 -> "ZMM25"
  | ZMM26 -> "ZMM26"
  | ZMM27 -> "ZMM27"
  | ZMM28 -> "ZMM28"
  | ZMM29 -> "ZMM29"
  | ZMM30 -> "ZMM30"
  | ZMM31 -> "ZMM31"
  | FLAGS -> "FLAGS"
  | EFLAGS -> "EFLAGS"
  | RFLAGS -> "RFLAGS"
  | IP -> "IP"
  | EIP -> "EIP"
  | RIP -> "RIP"
  | ES -> "ES"
  | CS -> "CS"
  | SS -> "SS"
  | DS -> "DS"
  | FS -> "FS"
  | GS -> "GS"
  | GDTR -> "GDTR"
  | LDTR -> "LDTR"
  | IDTR -> "IDTR"
  | TR -> "TR"
  | TR0 -> "TR0"
  | TR1 -> "TR1"
  | TR2 -> "TR2"
  | TR3 -> "TR3"
  | TR4 -> "TR4"
  | TR5 -> "TR5"
  | TR6 -> "TR6"
  | TR7 -> "TR7"
  | CR0 -> "CR0"
  | CR1 -> "CR1"
  | CR2 -> "CR2"
  | CR3 -> "CR3"
  | CR4 -> "CR4"
  | CR5 -> "CR5"
  | CR6 -> "CR6"
  | CR7 -> "CR7"
  | CR8 -> "CR8"
  | CR9 -> "CR9"
  | CR10 -> "CR10"
  | CR11 -> "CR11"
  | CR12 -> "CR12"
  | CR13 -> "CR13"
  | CR14 -> "CR14"
  | CR15 -> "CR15"
  | DR0 -> "DR0"
  | DR1 -> "DR1"
  | DR2 -> "DR2"
  | DR3 -> "DR3"
  | DR4 -> "DR4"
  | DR5 -> "DR5"
  | DR6 -> "DR6"
  | DR7 -> "DR7"
  | DR8 -> "DR8"
  | DR9 -> "DR9"
  | DR10 -> "DR10"
  | DR11 -> "DR11"
  | DR12 -> "DR12"
  | DR13 -> "DR13"
  | DR14 -> "DR14"
  | DR15 -> "DR15"
  | K0 -> "K0"
  | K1 -> "K1"
  | K2 -> "K2"
  | K3 -> "K3"
  | K4 -> "K4"
  | K5 -> "K5"
  | K6 -> "K6"
  | K7 -> "K7"
  | BND0 -> "BND0"
  | BND1 -> "BND1"
  | BND2 -> "BND2"
  | BND3 -> "BND3"
  | BNDCFG -> "BNDCFG"
  | BNDSTATUS -> "BNDSTATUS"
  | MXCSR -> "MXCSR"
  | PKRU -> "PKRU"
  | XCR0 -> "XCR0"

(* }}} *)
